name: quotes
description: simple crud app
version: 0.0.1
environment:
  sdk: '>=2.12.0'
dependencies:
  uuid: ^2.0.3
  postgres: ^2.1.1
  logging: ^1.0.0-nullsafety.0
  mockito: ^4.0.0
  test: 1.16.0-nullsafety.13
