version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.4.1
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - cluster.name=demo-es
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  backend:
    build: ./quotes-be/
    ports:
    - "5050:5050"
    links:
    - elasticsearch
    depends_on:
    - elasticsearch

  frontend:
    build: ./quotes-fe/
    ports:
    - "8080:8080"
    links:
    - backend
    depends_on:
    - backend