version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.12.0
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - cluster.name=demo-es
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1


  backend:
    build: ./quotesbe2/
    ports:
    - "5050:5050"
    environment:
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
    - ELASTICSEARCH_AUTHOR_INDEX=authors
    - ELASTICSEARCH_AUTHOR_EVENTS_INDEX=author_events
    - ELASTICSEARCH_BOOK_INDEX=books
    - ELASTICSEARCH_BOOK_EVENTS_INDEX=book_events
    - ELASTICSEARCH_QUOTE_INDEX=quotes
    - ELASTICSEARCH_QUOTE_EVENTS_INDEX=quote_events
    links:
    - elasticsearch
    depends_on:
    - elasticsearch

#  frontend:
#    build: ./quotes-fe/
#    ports:
#    - "8080:8080"
#    links:
#    - backend
#    depends_on:
#    - backend

#  frontend2:
#    build: ./quotesfe2/
#    ports:
#    - "8000:8000"
#    links:
#    - backend
#    depends_on:
#    - backend
