targets:
  $default:
    builders:
      quotes_fe|constant_builder:
        options:
          backendHost: http://localhost:5050
          
        dev_options:
          backendHost: http://localhost:5050

builders:
  constant_builder:
    import: "package:quotes_fe/builder.dart"
    builder_factories: ["constantBuilder"]
    build_to: source
    build_extensions:
      "$lib$": ["generated_consts.dart"]