name: quotes_fe
description: Frontend for Quotes app
version: 0.0.1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  angular: ^6.0.0-alpha
  angular_router: ^2.0.0-alpha+23
  angular_forms: ^2.0.0
  analyzer: ^0.36.2
  logging: ^0.11.3+2
  uuid: ^1.0.3
  http: ^0.12.0
dev_dependencies:
  # angular_test: ^2.0.0
  # build_test: ^0.10.2
  # test: ^1.0.0
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0