name: quotesbe
publish_to: none 

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  logging: ^1.2.0
  uuid: ^4.3.3
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.25.2

dev_dependencies:
  http: ^1.2.1
  lints: ^3.0.0
  test_process: ^2.1.0

